openapi: 3.0.0
info:
  title: Book Service
  version: 1.0.0
  description: API documentation for the Book Service
servers:
  - url: http://localhost:7000/v1/book-service
    description: Local development server
components:
  schemas:
    BookResponse:
      $ref: './schemas/books.yaml#/BookResponse'
    CreateBookRequest:
      $ref: './schemas/books.yaml#/CreateBookRequest'
    UpdateBookRequest:
      $ref: './schemas/books.yaml#/UpdateBookRequest'
    ListBooksResponse:
      $ref: './schemas/books.yaml#/ListBooksResponse'
    EmployeeResponse:
      $ref: './schemas/employees.yaml#/EmployeeResponse'
    CreateEmployeeRequest:
      $ref: './schemas/employees.yaml#/CreateEmployeeRequest'
    UpdateEmployeeRequest:
      $ref: './schemas/employees.yaml#/UpdateEmployeeRequest'
    ListEmployeesResponse:
      $ref: './schemas/employees.yaml#/ListEmployeesResponse'
    ErrorResponse:
      $ref: './schemas/books.yaml#/ErrorResponse'
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
paths:
  /books/create:
    $ref: "./paths/books.yaml#/create"
  /books/update/{id}:
    $ref: "./paths/books.yaml#/update"
  /books/delete/{id}:
    $ref: "./paths/books.yaml#/delete"
  /books/get/{id}:
    $ref: "./paths/books.yaml#/getbyid"
  /employees/create:
    $ref: "./paths/employees.yaml#/create"
  /employees/update/{id}:
    $ref: "./paths/employees.yaml#/update"
  /employees/delete/{id}:
    $ref: "./paths/employees.yaml#/delete"
  /employees/get/{id}:
    $ref: "./paths/employees.yaml#/getbyid"